#128, 128, 128 - Gray Glow , i.e used in idk
#97, 194, 247 - light sky blueish glow i.e used in melee weapon pickups
#27, 89, 130 - dark blue teal color i.e used in Thrown weapon pickups
#149, 194, 24 - bright yellow green glow i.e used in pistol pickups
#45, 155, 90 -  Medium green glow i.e used in shotgun pickups
#255, 227, 79 - bright yellow gold glow i.e used in SMG pickups
#254, 137, 0 - Orange Glow i.e used in AR Pickups
#249, 131, 215 - Light Pinkish Glow i.e used in Sniper Pickups
#164, 40, 178 - Dark pinkish Purple i.e used in heavy weap Pickups
#69, 69, 69 - Dark grey glow i.e used in jetpack pickup
#255, 100, 100 - Soft Red i.e used in health pickups
#128, 255, 128 -  Bright Green i.e used in armor pickups
#100, 255, 100 - neon lime green i.e used in property buying pickup
#100, 100, 255 - medium blue i.e used in property locked pickup
#255, 255, 100 - lemon yellow i.e used in dollar pickup and bribe pickup but without corona ring
#255, 139, 244 - purple glow i.e used in Snapshot pickup but without corona ring
#166, 226, 210 - light blue glow i.e used in camera,fire extinguisher pickup
#243, 68, 103 - Sexy Red Glow i.e used in sex or gift weapons pickups
#58, 61, 217 - deep Blue - used in Parachute type weapon pickups 
# you can also add only center glow pickups like this
# [OnlyGlow]
#  371=0   0 meaning disabled 1 meaning enabled
[AddonWeapons]
371=243, 68, 103