###################################################################################################
#        GANG WARS FIXES
###################################################################################################

[Mod]
Enabled = 1 # (0|1) Enable this mod.


[Gang Wars]

# Gang blip colours
CustomGangBlipColors                       = 1 # (0|1) Allows custom radar blip colours for each gang pedType.
Gang1_BlipColor                            = 0xC800C8 # Ballas
Gang2_BlipColor                            = 0x46C800 # Grove Street Families
Gang3_BlipColor                            = 0xFFC800 # Los Santos Vagos
Gang4_BlipColor                            = 0x0000C8 # San Fierro Rifa
Gang5_BlipColor                            = 0xFF8000 # Da Nang Boys
Gang6_BlipColor                            = 0x202020 # Mafia
Gang7_BlipColor                            = 0xFF0000 # Mountain Cloud Triad
Gang8_BlipColor                            = 0x00C8FF # Varrio Los Aztecas
Gang9_BlipColor                            = 0xFFFFFF # Gang 9
Gang10_BlipColor                           = 0xFFFFFF # Gang 10

# Gang war start / enemy selection
FixBlockOverlappingGangWars                = 1 # (0|1) Prevents starting another gang war or hood attack while one is already active.

FixUnrelatedGangsAttackCJ                  = 1 # (0|1) Only the current enemy gang can attack the player during gang wars.
RemoveEnemyGangFromPlayerGroups            = 1 # (0|1) Requires "FixUnrelatedGangsAttackCJ". Removes current enemy gang members from player groups.

FixExGangWarsNonCombatTerritoryProtection  = 1 # (0|1) For Extended Gang Wars. Prevents territories owned by gangs 4-10 marked as non-combatants (CanFightWith=0) from starting offensive gang wars.

# Territory / density
FixRefreshGangZonesAfterLoad               = 1 # (0|1) Fixes gang territory map colours not appearing after loading an exterior save.

FixDensityTransferOnDefenseFail            = 1 # (0|1) Makes Grove lose the same density amount that the enemy gains after a failed territory defense.
FullTerritoryLossOnDefenseFail             = 1 # (0|1) Requires "FixDensityTransferOnDefenseFail". Transfers all Grove density in the zone to the attacking gang.

# Attack vehicles
FixGangWarBikeVehicles                     = 1 # (0|1) Fixes gang war bikes being created as automobiles. Adds proper CBike support to gang attack vehicle spawning.

GangWarVehiclesTargetPlayer                = 1    # (0|1) Makes gang war attack vehicles with passengers chase the current player in focus instead of loosely roaming traffic routes.
GangWarVehicleChaseSpeed                   = 30.0 # Vehicle chase mission speed.
GangWarVehicleChaseMinDist                 = 5.0  # Chase lower distance threshold.
GangWarVehicleChaseMaxDist                 = 20.0 # Chase upper distance threshold.

FixGangWarDriveByRange                     = 1 # (0|1) Extends gang war vehicle passenger drive-by task range from vanilla 100.0 to a fixed internal value.