;---------------------------------------------------
;
; Improved Streaming by Junior_Djjr - MixMods.com.br
;
;---------------------------------------------------
; General settings
; Tip: Hold SHIFT before the game starts to bypass this mod.
;---------------------------------------------------

[Settings]
; Forces this streaming memory limit (the memory limit used to store files loaded into RAM, such as vehicles, world etc).
; In MB; the default is 50. The game supports up to 2048 (2 GB) but you can use "DoubleStreamingMemoryLimit" to double the limit by counting in half. Do not use 2048 (or close to it) without having "Largeaddress" installed (included in the Essentials Pack).
; You can find more information in the MixSets .ini file, but in short, you should set this number to the minimum necessary, with some margin. You need more if you use HD texture mods etc. You can see the usage using some mods, such as Open Limit Adjuster F5 key. It's normal for the game to reach its limit only after minutes of normal gameplay.
; It's exactly the same as MixSets and other mods do. The value here will replace the same value set in other mods.
; In some cases, if necessary, this mod will automatically increase this value for you, but it is recommended that you set it. It does NOT decrease it (if it is set higher in MixSets or another mod).
StreamMemoryForced = 1999

; Doubles the stream memory limit using a technique of counting half the file size, thus allowing the use of up to 4096 MB (4 GB) of stream memory. Other counters, such as those in Open Limit Adjuster, will also show half the actual value.
; By setting "1", you should configure "StreamMemoryForced" to half, for example "StreamMemoryForced = 1250" to use 2500 MB (2.5 GB). Don't use anything close to 3 GB because the game needs a RAM margin to function correctly (since other things in the game, including mods, can allocate memory not counted as streaming).
DoubleStreamingMemoryLimit = 0

; The game will force the release of RAM by unloading unused models if it reaches a value above this total RAM memory of the game process.
; Normally the game has problems when RAM usage is close to or greater than 3.5 GB. For safety, a value like "3100" (3.1 GB) is stable, but if there are problems, such as the map stopping loading and textures disappearing from the pause menu, lower it even further.
MaxRAM = 1999

; Preloads all LODs (low definition objects seen from afar).
; This fixes holes in the map caused by delay in loading models.
PreLoadLODs = 1

; Preload all animations (.ifp files).
; Not so useful for a normal game, but it can be useful for SAMP.
; WARNING: May cause a crash that seems to be related to limits (already documented in CrashInfo), only enable it if there is a solution.
PreLoadAnims = 0

; If the streaming memory usage exceeds this percentage, the mod will start to gradually flush unused models to free up memory.
; Originally the game only removes when it reaches the limit (which increases the work of streaming, delaying and causing stuttering), this function prevents the limit from being reached. The same will also be called if the "MaxRAM" is reached.
RemoveUnusedWhenPercent = 90

; Delay time to unload each unused model when reaching "RemoveUnusedWhenPercent".
; In case the memory usage is close to the limit, the mod will automatically halve the delay.
; You can use "0" to unload every frame, but this can also increase streaming work.
RemoveUnusedIntervalMs = 120

; 1 = Lists in the .log file all models being loaded. It will delay the game loading. Use it if you think a model is crashing when loading it, preferably with "LoadEach = 1" in the ranges below.
; 0 = Small .log file with little information (such as warnings).
; -1 = Does not generate .log.
LogMode = 0


;---------------------------------------------------
; Preload Ranges
; Preloads some models so don't need to load during game play. Increases RAM usage but decreases disk usage and file streaming work.
; Feel free to configure or disable them to your liking and need, or create more of them.
;---------------------------------------------------

;--- Descriptions:
; - Enabled
; Enables/disables loading this range.
; - LoadEach
; Load the files every quantity. Using 0 or 1 may delay the game's loading a bit. Something between 10 and 50 is good.
; - KeepLoaded
; Force it to keep loaded forever, so for example not being unloaded with "RemoveUnusedWhenPercent" etc.
; - Start
; ID of the initial model to be loaded. You can find the definition of IDs in your game's .ide files.
; - End
; ID of the final model to be loaded.
; - IfBiggerThan
; Only load if the model is BIGGER than this amount of KB. Use 0 to disable. Anything over 1000 will only load files larger than 1MB (typically HD mods).
; - IfSmallerThan
; Only load if the model is SMALLER than this amount of KB. Use 0 to disable. Anything below 6 will only load LODs and light models. Detail that the necessary .txd are loaded together with the .dff.
; - IgnorePedGroup
; For pedestrians. Skips loading the model if it is from this pedgroup number. Useful for ignoring drug dealers (pedgroup 29) as the game always creates the latest loaded vendor model. Keep 0 for non-pedestrian model ranges.
;---

;---------------------------------------------------
; Map
; EXPERIMENTAL: May cause problems.
; CAUTION! This is where practically all your game files are set.
; It is recommended to set "IfSmallerThan" or "IfBiggerThan", otherwise in vanilla game without mods you will need at least 1024 streaming memory, and if you use large file mods like RoSA, even 2048 may not be enough.
; With "IfSmallerThan=6" in vanilla game you will need at least 512 MB.
; It may delay game loading. You might want to disable it with "Enabled=0".
[Range1]
Enabled = 0
LoadEach = 50
KeepLoaded = 1
Start = 2900
End   = 18630
IgnoreStart = 14300  ; Start to ignore some interior objects
IgnoreEnd   = 15100  ; End to ignore interior objects
IfBiggerThan  = 0
IfSmallerThan = 6
IgnorePedGroup = 0

; Vehicles
; ATTENTION: You need some limit adjuster, like the Open Limit Adjuster, to increase the Vehicle Structs limit.
; WARNING: Currently causing issues with not appearing vehicles in certain areas, "Streaming_DesiredNumberOfVehiclesLoaded" from f92la currently improves but does not fully resolve. Only activate if there is a solution.
; Tip: If you have some heavy cars mods that are lag-spiking during gameplay, you might want to load those cars by setting the IfBiggerThan to something like "IfBiggerThan = 20000".
[Range2]
Enabled = 0
LoadEach = 10
KeepLoaded = 1
Start = 400
End   = 611
IgnoreStart = 0
IgnoreEnd   = 0
IfBiggerThan  = 0
IfSmallerThan = 0
IgnorePedGroup = 0

; Pedestrians
[Range3]
Enabled = 1
LoadEach = 10
KeepLoaded = 1
Start = 9
End   = 288
IgnoreStart = 0
IgnoreEnd   = 0
IfBiggerThan  = 0
IfSmallerThan = 0
IgnorePedGroup = 29  ; Ignore drug dealers (29) as the game always creates the last loaded.

; Vegetation.
; There are others in other IDs, but here it covers almost all of them.
[Range4]
Enabled = 1
LoadEach = 10
KeepLoaded = 1
Start = 615
End   = 792
IgnoreStart = 0
IgnoreEnd   = 0
IfBiggerThan  = 0
IfSmallerThan = 0
IgnorePedGroup = 0

; Procedural objects
; Some plants, stones, etc.
[Range5]
Enabled = 1
LoadEach = 10
KeepLoaded = 1
Start = 800
End   = 906
IgnoreStart = 0
IgnoreEnd   = 0
IfBiggerThan  = 0
IfSmallerThan = 0
IgnorePedGroup = 0

; Prop objects
; Dumpsters, poles, etc.
[Range6]
Enabled = 1
LoadEach = 10
KeepLoaded = 1
Start = 1207
End = 1698
IgnoreStart = 0
IgnoreEnd   = 0
IfBiggerThan  = 0
IfSmallerThan = 0
IgnorePedGroup = 0

