##############################################
# Ped Skills by Junior_Djjr - MixMods.com.br #
##############################################

# General settings
[General]

# Multiply range of weapons range (for example 2.0 is double)
WeaponRangeMult     = 4.0    # Firing range (MIXSETS REPLACES WHEN SETTING IN IT)
WeaponAimMult       = 1.5    # Aiming range
 
# Multiply shooting accuracy of the game
AccuracyMult        = 1.3    # General
PlayerAccuracyMult  = 1.0    # Player
ShotgunAccuracyMult = 1.2    # Shotgun

# Adjust accuracy based on the target's situation
AccuracyVelocityFactor = 1.2   # The higher, NPCs will have more difficulty with moving targets.
AccuracyDistanceFactor = 1.2   # The higher, NPCs will have more difficulty with a distant target.
AccuracyOnVehicleFactor = 1.2  # The higher, NPCs will have more difficulty if it's in a vehicle (drive-by).
AccuracyOnJetpackFactor = 1.5  # The higher, NPCs will have more difficulty hitting if the player is using jetpack. Increasing it helps facilitate missions like "Black Project".
PlayerVehMissionDamMult = 0.7  # Multiplies player vehicle damage during missions. Decreasing it helps make missions like "Just Business" and "Drive By" easier.


# Default NPC skills
[Default skills]

# Attack rate
AttackRate          = 50     # (40) General
CopsAttackRate      = 50     # (30) Cops
SwatAttackRate      = 60     # (70) SWAT
FBIAttackRate       = 70     # (60) FBI
ArmyAttackRate      = 80     # (80) Army
ScriptAttackMult    = 1.1    # Multiply value set by scripts (like missions)

# Weapon skill (up to 3)
WeaponSkill         = 1      # (1) General

# Fighting style
FightingStyle       = 4      # (4) General

# Weapon shot accuracy
WeaponAccuracy      = 70     # (60) General
CopsWeaponAccuracy  = 80     # (60) Cops
SwatWeaponAccuracy  = 90     # (60) SWAT
FBIWeaponAccuracy   = 90     # (76) FBI
ArmyWeaponAccuracy  = 90     # (84) Army
ScriptAccuracyMult  = 1.1    # Multiply value set by scripts (like missions)

# Seeing distance
SeeingRange         = 30.0   # (15.0) General
GangsSeeingRange    = 60.0   # (40.0) Gangs

# Hearing distance
HearingRange        = 30.0   # (15.0) General
GangsHearingRange   = 60.0   # (40.0) Gangs

# Scanning radius of nearby peds for decision maker
DmRadius            = 30.0   # (15.0) General
CopsDmRadius        = 100.0  # (60.0) Cops

# Number of nearby peds to scan
DmPedsToScan        = 5      # (3) General
CopsDmPedsToScan    = 10     # (8) Cops

# Armour
CopsArmour          = 50.0   # (0.0) Cops
SwatArmour          = 50.0   # (50.0) SWAT
FBIArmour           = 100.0  # (100.0) FBI
ArmyArmour          = 100.0  # (100.0) Army
