[Settings]
RecursiveVariations=1
UseParentVoices=0
EnableCloneRemover=0
CloneRemoverDisableOnMission=1
CloneRemoverIncludeVehicleOccupants=1
CloneRemoverSpawnDelay=3
CloneRemoverIncludeVariations=
#CloneRemoverExcludeModels=102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,120,121,122,123,124,125,126,127,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288

# Settings by rixgeo - feel free to weak.
# If somehow, for some reason you have issues with a specific ped in a mission or missions, put "DisableOnMission=1" in the config.
# If you want to disable a ped either delete the model, or comment the config out like shown bellow.

#Example:
# [vla1]
# Global=vla1,vla1_1
# MergeInteriorsWithCitiesAndZones=1
# DisableOnMission=1

;Law Enforcement
[army]
Global=army,army1,army2,army3,army4
MergeInteriorsWithCitiesAndZones=1
[army1,army2,army3,army4]
Voice=army

[swat]
Global=swat,swat2,swat3
MergeInteriorsWithCitiesAndZones=1
[swat2,swat3]
Voice=swate

[lapd1]
Global=lapd1,lapd1_2
MergeInteriorsWithCitiesAndZones=1
[lapd1_2]
Voice=lapd1

[sfpd1]
Global=sfpd1,sfpd1_2
MergeInteriorsWithCitiesAndZones=1
[sfpd1_2]
Voice=sfpd1


;Regular peds
[bmyap]
LosSantos=bmyap
SanFierro=somyap
LasVenturas=vwmyap

[wmycd1]
Global=wmycd1,wmycd2
[wmycd2]
Voice=wmycd1

[bfybu]
Global=bfybu,bfybu2
MergeInteriorsWithAreasAndZones=1
[bfybu2]
Voice=bfybu

[bfypro]
Global=bfypro,bfypro2
MergeInteriorsWithAreasAndZones=1
[bfypro2]
Voice=bfypro

[bmyboun]
Global=bmyboun,bmyboun2
MergeInteriorsWithAreasAndZones=1
[bmyboun2]
Voice=bmyboun

[bmybu]
Global=bmybu,bmybu2
MergeInteriorsWithAreasAndZones=1
[bmybu2]
Voice=bmybu

[bmydj]
Global=bmydj,bmydj2
MergeInteriorsWithAreasAndZones=1
[bmydj2]
Voice=bmydj

[bmyri]
Global=bmyri,bmyri2
MergeInteriorsWithAreasAndZones=1
[bmyri2]
Voice=bmyri

[hfyri]
Global=hfyri,hfyri2
MergeInteriorsWithAreasAndZones=1
[hfyri2]
Voice=hfyri

[hmycr]
Global=hmycr,hmycr2
MergeInteriorsWithAreasAndZones=1
[hmycr2]
Voice=hmycr

[hmyri]
Global=hmyri,hmyri2
MergeInteriorsWithAreasAndZones=1
[hmyri2]
Voice=hmyri

[hmyst]
Global=hmyst,hmyst2
MergeInteriorsWithAreasAndZones=1
[hmyst2]
Voice=hmyst

[omokung]
Global=omokung,omokung2
MergeInteriorsWithAreasAndZones=1
[omokung2]
Voice=omokung

[sfypro]
Global=sfypro,sfypro2
MergeInteriorsWithAreasAndZones=1
[sfypro2]
Voice=sfypro

[shmycr]
Global=shmycr,shmycr2
MergeInteriorsWithAreasAndZones=1
[shmycr2]
Voice=shmycr

[sofybu]
Global=sofybu,sofybu2
MergeInteriorsWithAreasAndZones=1
[sofybu2]
Voice=sofybu

[sofyri]
Global=sofyri,sofyri2
MergeInteriorsWithAreasAndZones=1
[sofyri2]
Voice=sofyri

[somybu]
Global=somybu,somybu2
MergeInteriorsWithAreasAndZones=1
[somybu2]
Voice=somybu

[swmost]
Global=swmost,swmost2
MergeInteriorsWithAreasAndZones=1
[swmost2]
Voice=swmost

[swmyri]
Global=swmyri,swmyri2
MergeInteriorsWithAreasAndZones=1
[swmyri2]
Voice=swmyri

[vbfypro]
Global=vbfypro,vbfypro2
MergeInteriorsWithAreasAndZones=1
[vbfypro2]
Voice=vbfypro

[vbmybox]
Global=vbmybox,vbmybox2
MergeInteriorsWithAreasAndZones=1
[vbmybox2]
Voice=vbmybox

[vhfypro]
Global=vhfypro,vhfypro2
MergeInteriorsWithAreasAndZones=1
[vhfypro2]
Voice=vhfypro

[vwfywai]
Global=vwfywai,vwfywai2
MergeInteriorsWithAreasAndZones=1
[vwfywai2]
Voice=vwfywai2

[vwmybox]
Global=vwmybox,vwmybox2
MergeInteriorsWithAreasAndZones=1
[vwmybox2]
Voice=vwmybox

[wbdyg1]
Global=wbdyg1,wbdyg1a
MergeInteriorsWithAreasAndZones=1
[wbdyg1a]
Voice=wbdyg1

[wbdyg2]
Global=wbdyg2,wbdyg2a
MergeInteriorsWithAreasAndZones=1
[wbdyg2a]
Voice=wbdyg2

[wfyburg]
Global=wfyburg,wfyburg2
MergeInteriorsWithAreasAndZones=1
[wfyburg2]
Voice=wfyburg

[wfyclot]
Global=wfyclot,wfyclot2
MergeInteriorsWithAreasAndZones=1
[wfyclot2]
Voice=wfyclots

[wfyri]
Global=wfyri,wfyri2
MergeInteriorsWithAreasAndZones=1
[wfyri2]
Voice=wfyri

[wmori]
Global=wmori,wmori2
MergeInteriorsWithAreasAndZones=1
[wmori2]
Voice=wmori

[wmost]
Global=wmost,wmost2
MergeInteriorsWithAreasAndZones=1
[wmost2]
Voice=wmost

[wmybell]
Global=wmybell,wmybell2
MergeInteriorsWithAreasAndZones=1
[wmybell2]
Voice=wmybell

[wmybp]
Global=wmybp,wmybp2
MergeInteriorsWithAreasAndZones=1
[wmybp2]
Voice=wmybp

[vhmycr]
Global=vhmycr,vhmycrb
MergeInteriorsWithAreasAndZones=1
[vhmycrb]
Voice=vhmycr

[wmydrug]
Global=wmydrug,wmydrug2
MergeInteriorsWithAreasAndZones=1
[wmydrug2]
Voice=wmydrug

[wmyjg]
Global=wmyjg,wmyjga
MergeInteriorsWithAreasAndZones=1
[wmyjga]
Voice=wmyjg

[wmymoun]
Global=wmymoun,wmymoun2
MergeInteriorsWithAreasAndZones=1
[wmymoun2]
Voice=wmymoun

[bmydrug]
Global=bmydrug,bmydrug_2
MergeInteriorsWithAreasAndZones=1
[bmydrug_2]
Voice=bmydrug

[bmyst]
Global=bmyst,bmyst2
MergeInteriorsWithAreasAndZones=1
[bmyst2]
Voice=bmyst

[cwfyhb]
Global=cwfyhb,cwfyhb2
MergeInteriorsWithAreasAndZones=1
[cwfyhb2]
Voice=cwfyhb

[hfypro]
Global=hfypro,hfypro2
MergeInteriorsWithAreasAndZones=1
[hfypro2]
Voice=hfypro

[hmori]
Global=hmori,hmori2
MergeInteriorsWithAreasAndZones=1
[hmori2]
Voice=hmori

[wmysgrd]
Global=wmysgrd,wmysgrd2
MergeInteriorsWithAreasAndZones=1
[wmysgrd2]
Voice=wmysgrd

[swmyhp2]
Global=swmyhp2,swmyhp3
MergeInteriorsWithAreasAndZones=1
[swmyhp3]
Voice=swmyhp2

[bmypol1]
Global=bmypol1,bogman,bmypol1_2,bmypol2_2
MergeInteriorsWithAreasAndZones=1
[bogman,bmypol1_2,bmypol2_2]
Voice=bmypol1


;Gangs - Families
[fam1]
Global=fam1,fam1a,fam1b,fam1c,fam1d,fam1e
MergeInteriorsWithAreasAndZones=1
PLS=sev1
LIND3=sev1
LIND4A=sev1
LIND4C=sev1
LDOC2=sev1
LDOC3A=sev1
LDOC3C=sev1
EBE3C=sev1
VIN2=tem1
SUN1=tem1
SUN2=tem1
SUN4=tem1
SUN3C=tem1
SUN3B=tem1
SUN3A=tem1
VERO1=tem1
VERO2=tem1
VERO3=tem1
VERO4A=tem1
VERO4B=tem1
SMB1=tem1
SMB2=tem1
[fam1,fam1a,fam1b,fam1c,fam1d,fam1e,sev1,tem1]
Voice=fam1

[fam2]
Global=fam2,dope,fam2a,fam2b
MergeInteriorsWithAreasAndZones=1
PLS=sev2
LIND3=sev2
LIND4A=sev2
LIND4C=sev2
LDOC2=sev2
LDOC3A=sev2
LDOC3C=sev2
EBE3C=sev2
VIN2=tem2
SUN1=tem2
SUN2=tem2
SUN4=tem2
SUN3C=tem2
SUN3B=tem2
SUN3A=tem2
VERO1=tem2
VERO2=tem2
VERO3=tem2
VERO4A=tem2
VERO4B=tem2
SMB1=tem2
SMB2=tem2
[fam2,dope,fam2a,fam2b,sev2,tem2]
Voice=fam2

[fam3]
Global=fam3,fam3a,fam3b,fam3c,fam3d
MergeInteriorsWithAreasAndZones=1
PLS=sev3
LIND3=sev3
LIND4A=sev3
LIND4C=sev3
LDOC2=sev3
LDOC3A=sev3
LDOC3C=sev3
EBE3C=sev3
VIN2=tem3
SUN1=tem3
SUN2=tem3
SUN4=tem3
SUN3C=tem3
SUN3B=tem3
SUN3A=tem3
VERO1=tem3
VERO2=tem3
VERO3=tem3
VERO4A=tem3
VERO4B=tem3
SMB1=tem3
SMB2=tem3
[fam3,fam3a,fam3b,fam3c,fam3d,sev3,tem3]
Voice=fam3


;Gangs - Ballas
[ballas1]
Global=ballas1,ballas1a,ballas1b,ballas1c,ballas1d
MergeInteriorsWithAreasAndZones=1
GLN1=ktb1
GLN1B=ktb1
GLN2A=ktb1
JEF1A=ktb1
JEF1B=ktb1
JEF2=ktb1
JEF3B=ktb1
LIND1A=ktb1
LIND1B=ktb1
LIND2A=ktb1
LIND3=ktb1
LIND4A=ktb1
LIND4C=ktb1
PLS=ktb1
LDOC2=ktb1
GAN1=ktb1
GAN2=ktb1
ELS1A=rhb1
ELS1B=rhb1
ELS2=rhb1
ELS3B=rhb1
JEF3C=rhb1
VIN2=tdb1
SUN1=tdb1
SUN2=tdb1
SUN4=tdb1
SUN3C=tdb1
SUN3B=tdb1
SUN3A=tdb1
VERO1=tdb1
VERO2=tdb1
VERO3=tdb1
VERO4A=tdb1
VERO4B=tdb1
SMB1=tdb1
SMB2=tdb1
[ballas1a,ballas1b,ballas1c,ballas1d,ktb1,rhb1,tdb1]
Voice=ballas1

[ballas2]
Global=ballas2,ballas2a,ballas2b,ballas2c
MergeInteriorsWithAreasAndZones=1
GLN1=ktb2
GLN1B=ktb2
GLN2A=ktb2
JEF1A=ktb2
JEF1B=ktb2
JEF2=ktb2
JEF3B=ktb2
LIND1A=ktb2
LIND1B=ktb2
LIND2A=ktb2
LIND3=ktb2
LIND4A=ktb2
LIND4C=ktb2
PLS=ktb2
LDOC2=ktb2
GAN1=ktb2
GAN2=ktb2
ELS1A=rhb2
ELS1B=rhb2
ELS2=rhb2
ELS3B=rhb2
JEF3C=rhb2
VIN2=tdb2
SUN1=tdb2
SUN2=tdb2
SUN4=tdb2
SUN3C=tdb2
SUN3B=tdb2
SUN3A=tdb2
VERO1=tdb2
VERO2=tdb2
VERO3=tdb2
VERO4A=tdb2
VERO4B=tdb2
SMB1=tdb2
SMB2=tdb2
[ballas2a,ballas2b,ballas2c,ktb2,rhb2,tdb2]
Voice=ballas2

[ballas3]
Global=ballas3,ballas3a,ballas3b,ballas3c
MergeInteriorsWithAreasAndZones=1
GLN1=ktb3
GLN1B=ktb3
GLN2A=ktb3
JEF1A=ktb3
JEF1B=ktb3
JEF2=ktb3
JEF3B=ktb3
LIND1A=ktb3
LIND1B=ktb3
LIND2A=ktb3
LIND3=ktb3
LIND4A=ktb3
LIND4C=ktb3
PLS=ktb3
LDOC2=ktb3
GAN1=ktb3
GAN2=ktb3
ELS1A=rhb3
ELS1B=rhb3
ELS2=rhb3
ELS3B=rhb3
JEF3C=rhb3
VIN2=tdb3
SUN1=tdb3
SUN2=tdb3
SUN4=tdb3
SUN3C=tdb3
SUN3B=tdb3
SUN3A=tdb3
VERO1=tdb3
VERO2=tdb3
VERO3=tdb3
VERO4A=tdb3
VERO4B=tdb3
SMB1=tdb3
SMB2=tdb3
[ballas3a,ballas3b,ballas3c,ktb3,rhb3,tdb3]
Voice=ballas3


;Gangs - Aztecas
[vla1]
Global=vla1,vla1_1
MergeInteriorsWithAreasAndZones=1
LMEX1A=lma1
LMEX1B=lma1
MAR1=lma1
MAR2=lma1
MAR3=lma1
[vla1_1,lma1]
Voice=vla1

[vla2]
Global=vla2,vla2_2
MergeInteriorsWithAreasAndZones=1
LMEX1A=lma2
LMEX1B=lma2
MAR1=lma2
MAR2=lma2
MAR3=lma2
[vla2_2,lma2]
Voice=vla2

[vla3]
Global=vla3,vla3_3
MergeInteriorsWithAreasAndZones=1
LMEX1A=lma3
LMEX1B=lma3
MAR1=lma3
MAR2=lma3
MAR3=lma3
[vla3_3,lma3]
Voice=vla3


;Gangs - Vagos
[lsv1]
Global=lsv1,lsv1_1
MergeInteriorsWithAreasAndZones=1
CHC1A=lcv1
CHC1B=lcv1
CHC2A=lcv1
CHC2B=lcv1
CHC3=lcv1
CHC4B=lcv1
CHC4A=ebv1
EBE1=ebv1
EBE2=ebv1
EBE3C=ebv1
[lsv1_1,lcv1,ebv1]
Voice=lsv1

[lsv2]
Global=lsv2,lsv2_2
MergeInteriorsWithAreasAndZones=1
CHC1A=lcv2
CHC1B=lcv2
CHC2A=lcv2
CHC2B=lcv2
CHC3=lcv2
CHC4B=lcv2
CHC4A=ebv2
EBE1=ebv2
EBE2=ebv2
EBE3C=ebv2
[lsv2_2,lcv1,ebv2]
Voice=lsv2

[lsv3]
Global=lsv3,lsv3_3
MergeInteriorsWithAreasAndZones=1
CHC1A=lcv3
CHC1B=lcv3
CHC2A=lcv3
CHC2B=lcv3
CHC3=lcv3
CHC4B=lcv3
CHC4A=ebv3
EBE1=ebv3
EBE2=ebv3
EBE3C=ebv3
[lsv3_3,lcv3,ebv3]
Voice=lsv3


;Gangs - Rifas
[sfr1]
Global=sfr1
GARC=gar1
BATTP=gar1
SUNMA=gar1
MergeInteriorsWithAreasAndZones=1
[gar1]
Voice=sfr1

[sfr2]
Global=sfr2
GARC=gar2
BATTP=gar2
SUNMA=gar2
MergeInteriorsWithAreasAndZones=1
[gar2]
Voice=sfr2

[sfr3]
Global=sfr3
GARC=gar3
BATTP=gar3
SUNMA=gar3
MergeInteriorsWithAreasAndZones=1
[gar3]
Voice=sfr3


;Gangs - Triads
[triada]
Global=triada,triadc
MergeInteriorsWithAreasAndZones=1
[triadc]
Voice=triada

[triadb]
Global=triadb,triadd
MergeInteriorsWithAreasAndZones=1
[triadd]
Voice=triadb

[triboss]
Global=triboss,triboss2,triboss3
MergeInteriorsWithAreasAndZones=1
[triboss2,triboss3]
Voice=triboss2


;Gangs - Italian Mafia
[vmaff1]
Global=vmaff1,mafgoon
MergeInteriorsWithAreasAndZones=1
[mafgoon]
Voice=vmaff1

[vmaff2]
Global=vmaff2,mafgoon2
MergeInteriorsWithAreasAndZones=1
[mafgoon2]
Voice=vmaff2

[vmaff3]
Global=vmaff3,vmaff3_1,mafgoon3
MergeInteriorsWithAreasAndZones=1
[vmaff3_1,mafgoon3]
Voice=vmaff3

[vmaff4]
Global=vmaff4,mafgoon4
MergeInteriorsWithAreasAndZones=1
[mafgoon4]
Voice=vmaff4


;Gangs - Da Nang Boys
[dnb2]
Global=dnb2,dnb4
MergeInteriorsWithAreasAndZones=1
[dnb4]
Voice=dnb2


;Gangs - San Andreas Bikers
[bikera]
LosSantos=lsbik1
SanFierro=sfbik1
LasVenturas=lvbik1
FlintCounty=flin1
Whetstone=whets1
AngelPine=whets1
RedCounty=redc1
BoneCounty=bonc1
TierraRobada=bonc1
Desert=bonc1
MergeInteriorsWithAreasAndZones=1
[lsbik1,sfbik1,lvbik1,flin1,whets1,redc1,bonc1]
Voice=bikera

[bikerb]
LosSantos=lsbik2
SanFierro=sfbik2
LasVenturas=lvbik2
FlintCounty=flin2
Whetstone=whets2
AngelPine=whets2
RedCounty=redc2
BoneCounty=bonc2
TierraRobada=bonc2
Desert=bonc2
MergeInteriorsWithAreasAndZones=1
[lsbik2,sfbik2,lvbik2,flin2,whets2,redc2,bonc2]
Voice=bikerb

[wmycr]
LosSantos=lsbik3
SanFierro=sfbik3
LasVenturas=lvbik3
FlintCounty=flin3
Whetstone=whets3
AngelPine=whets3
RedCounty=redc3
BoneCounty=bonc3
TierraRobada=bonc3
Desert=bonc3
UseParentVoice=1
MergeInteriorsWithAreasAndZones=1
[[lsbik3,sfbik3,lvbik3,flin3,whets3,redc3,bonc3]
Voice=wmycr


;Fixes & New Additions
[csher]
Countryside=csher,cdeput
Desert=dsher
MergeInteriorsWithAreasAndZones=1
[cdeput,dsher]
Voice=csher

[lapdm1]
LosSantos=lapdm1
SanFierro=sfpdm1
LasVenturas=lvpdm1
MergeInteriorsWithAreasAndZones=1
[sfpdm1,lvpdm1]
Voice=lapdm1

[bmochil]
Voice=omost
SILLY3=omonood
SILLY4=omonood

[bmochil]
GARC=wmoice
Voice=wmoice

[bmochil]
CHINA=omonood
JUNIHI=omonood
Voice=omost

;Triads Fix
[163,164]
TRICAS=117
TRICAS=118
TRICAS=120