[Settings]
EnablePeds=1
EnableSpecialPeds=1
EnableVehicles=1
EnablePedWeapons=1
LoadSettingsImmediately=1
EnableStreamingFix=1
#CONTROLS
DisableKey=-1
ReloadKey=-1
#DEBUGGING
EnableLog=0
LogJumps=0
ForceEnable=0
LoadStage=1
TrackReferenceCounts=-1
[Limits]
ExtraObjectsDirLimit=4000
MaxModelID=20000
[Areas]
Countryside=RED,WHET,FLINTC
LosSantos=LA
SanFierro=SF
LasVenturas=VE
Desert=ROBAD,ROBAD1,BONE
TierraRobada=ROBAD,ROBAD1
BoneCounty=BONE
RedCounty=RED
Blueberry=BLUEB,BLUEB1
Montgomery=MONT,MONT1
Dillimore=DILLI
PalominoCreek=PALO
FlintCounty=FLINTC
Whetstone=WHET
AngelPine=ANGPI