[Settings]
ChangeCarGenerators=0
ChangeScriptedCars=0
DisablePayAndSpray=1
EnableLights=0
EnableSideMissions=1
EnableSiren=1
EnableSpecialFeatures=1
ExcludeCarGeneratorModels=492,600
ExcludeModelsFromInheritance=596,597,598,599,490,497,472,432,433
;Settings by rixgeo - feel free to tweak
;A max of 3 trailers per truck are allowed. If you try 4 or more, they won't spawn. Example: 591-591-591-591; This does not work.

;Tanker/Petrol
[514]
Trailers1=584
Global=Trailers1
TrailersSpawnChance=50

;Linerunner
[403]
Trailers1=435,450,584,591
Global=Trailers1
TrailersSpawnChance=50

;Roadtrain (Truck)
[515]
Trailers1=435,450,584,591
Global=Trailers1
TrailersSpawnChance=50

;Linerunner - Road train
[403]
Trailers1=435,450,584,591
Trailers2=[591-591-435]
Trailers3=[591-591-450]
Trailers4=[591-591-591]
LosSantos=Trailers1
SanFierro=Trailers1
LasVenturas=Trailers1
Blueberry=Trailers1
Montgomery=Trailers1
Dillimore=Trailers1
PalominoCreek=Trailers1
AngelPine=Trailers1
Global=Trailers1,Trailers2,Trailers3,Trailers4
TrailersSpawnChance=50

;Linerunner - Road train 2
[403]
Trailers1=435,450,584,591
Trailers2=[591-435]
Trailers3=[591-450]
Trailers4=[591-591]
LosSantos=Trailers1
SanFierro=Trailers1
LasVenturas=Trailers1
Blueberry=Trailers1
Montgomery=Trailers1
Dillimore=Trailers1
PalominoCreek=Trailers1
AngelPine=Trailers1
Global=Trailers1,Trailers2,Trailers3,Trailers4
TrailersSpawnChance=50

;Roadtrain (Truck) - Road train
[515]
Trailers1=435,450,584,591
Trailers2=[591-591-435]
Trailers3=[591-591-450]
Trailers4=[591-591-591]
LosSantos=Trailers1
SanFierro=Trailers1
LasVenturas=Trailers1
Blueberry=Trailers1
Montgomery=Trailers1
Dillimore=Trailers1
PalominoCreek=Trailers1
AngelPine=Trailers1
Global=Trailers1,Trailers2,Trailers3,Trailers4
TrailersSpawnChance=50

;Roadtrain (Truck) - Road train 2
[515]
Trailers1=435,450,584,591
Trailers2=[591-435]
Trailers3=[591-450]
Trailers4=[591-591]
LosSantos=Trailers1
SanFierro=Trailers1
LasVenturas=Trailers1
Blueberry=Trailers1
Montgomery=Trailers1
Dillimore=Trailers1
PalominoCreek=Trailers1
AngelPine=Trailers1
Global=Trailers1,Trailers2,Trailers3,Trailers4
TrailersSpawnChance=50

;Baggage
[485]
Trailers1=606,607,608
Global=Trailers1
TrailersSpawnChance=50

;Tug
[583]
Trailers1=606,607,608
Global=Trailers1
TrailersSpawnChance=50

;Utility Van
[552]
Trailers1=611
Global=Trailers1
TrailersSpawnChance=50
TrailersMatchColors=1

;Towtruck - Basic
[525]
Trailers1=400,436,445,496,507,516,547,549,600
Global=Trailers1
TrailersHealth=450
TrailersSpawnChance=50

;Tractor
[531]
Trailers1=610,611
Global=Trailers1
TrailersSpawnChance=50