[Settings]
; Author Mostafa

; ChanceRange Total range for random numbers (The Dice Size).
; Lower value (e.g., 500) = More frequent photos (Common).
; Higher value (e.g., 3000) = Less frequent photos (Rare).
ChanceRange=3000

; PhotoThreshold The number required to trigger a photo.
; IMPORTANT Must be slightly lower than 'ChanceRange' (e.g., by 5).
; Example If ChanceRange is 800 and Threshold is 795, numbers 796-800 will trigger a photo.
; Larger gap = More photos. Smaller gap = Fewer photos.
PhotoThreshold=2997