[MAIN]
; F12 key = id 123
on_off_key = 122

show_tags = true
show_oysters = true
show_horseshoes = true
show_snapshots = true
show_usjs = true
show_nearest = true

debug = false

[COLORS]
color_tag = 85 255 85 255
color_oyster = 255 255 153 255
color_horseshoe = 147 192 238 255
color_snapshot = 255 161 208 255
color_usj = 204 153 255 255

[EXTRA]
show_bribes = true
show_armours = false
show_weapons = false
color_bribe = 255 255 00 160
color_armour = 255 255 255 160
color_weapon = 48 48 48 160
enabled_on_startup = true
draw_dropped_weapons = false

[MODS]
show_dices = false
show_rampages = false
show_packets = false

color_dice = 0 0 255 255
color_rampage = 204 0 0 255
color_packet = 0 102 0 255

[CHALLENGE]
show_toys = true
show_chips = true
show_bridges = true
show_baloons = true
show_radios = true
show_carkeys = true
show_cctvs = true
show_moneybags = true
show_notes = false

color_toy = 255 255 0 255
color_chip = 147 192 238 255
color_bridge = 0 206 209 255
color_baloon = 255 0 0 255
color_radio = 0 8 255 255
color_carkey = 187 0 255 255
color_cctv = 34 127 0 255
color_moneybag = 255 106 0 255
color_note = 200 200 200 255