; SA Styled Speedometer v2
; By rill_

; Type "SPEEDO" while in a vehicle to reload this setting.

[Position]
Alignment = 1			; 0 = left. 1 = right, enables area and vehicle text x position patch.
; With radar
X = 65.0				; Default = 65.0
Y = 408.0				; Default = 408.0
; Without radar
X2 = 65.0				; Default = 65.0
Y2 = 408.0				; Default = 408.0
; Area and vehicle name text x position
; normal
AreaVehX = 130.0		; Default = 130.0
; with car tyre indicator
AreaVehX2 = 175.0		; Default = 175.0
; with motorcycle tyre indicator
AreaVehX3 = 155.0		; Default = 155.0

[Scale]
Mult = 1.1

[Speed]
; Speed text settings
OffsetX = 0.0
OffsetY = 5.0			; with extra bars = 5.0, no extra bars = 7.0
ScaleX = 0.3			; with extra bars = 0.25, no extra bars = 0.3
ScaleY = 0.6			; with extra bars = 0.5, no extra bars = 0.6
Font = 2				; 0 = Gothic, 1 = Subtitles, 2 = Menu font, 3 = Pricedown
Outline = 1

[Gear]
; Gear text settings
Enable = 1				; 0 = disable, 1 = enable
OffsetX = 1.0
OffsetY = -24.0			; with extra bars = -20.5, no extra bars = -24.0
ScaleX = 0.85			; with extra bars = 0.75, no extra bars = 0.85
ScaleY = 1.7			; with extra bars = 1.5, no extra bars = 1.7
Font = 2				; 0 = Gothic, 1 = Subtitles, 2 = Menu font, 3 = Pricedown
Outline = 2

[Units]
; Units text settings (kmh/mph text)
OffsetX = 0.0
OffsetY = 23.0          ; default = 23.0
ScaleX = 0.225          ; default = 0.225
ScaleY = 0.45           ; default = 0.45
Font = 2				; 0 = Gothic, 1 = Subtitles, 2 = Menu font, 3 = Pricedown
Outline = 1

[Vehicles]
; 0 = disable, 1 = enable
Car = 1
MonsterTruck = 1
Quadbike = 1
Helicopter = 0
Plane = 0
Boat = 0
Train = 1
Motorcycle = 1
Bicycle = 0

[Misc]
Indicators = 1			; 0 = disable, 1 = enable. Enable/disable indicators of engine, doors, tyres etc. 
RPMBar = 0				; 0 = plain, 1 = dashed bars
NitroEffect = 1			; 0 = disable, 1 = enable. Enable/disable nitro effect that change the rpm bar colour.
ExtraBars = 0			; 0 = disable, 1 = enable. Adds fuel and nitro bar. Required Gasoline mod by ArtemQa146 v2.6 or newer. Download here: https://libertycity.net/files/gta-san-andreas/207184-gasoline-mod.html
FuelBarColour = 1		; 0 = red, 1 = green, 2 = blue, 3 = light blue, 4 = white, 5 = black, 6 = brown, 7 = purple, 8 = grey, 9 = dark red, 10 = dark green, 11 = yellow, 12 = dark grey, 13 = blue (brighter) 14, light yellow
VehFuncsSpeed = 0	 	; 0 = disable, 1 = enable. Use VehFuncs speed calculation. Download here: https://www.mixmods.com.br/2023/01/sa-vehfuncs/
					
[Keys]
; set -1 to disable
Engine = 73				; Default = G (71)
Lights = 76				; Default = T (84)
Doors = 79				; Default = B (66)
Windows = 53			; Default = 5 (53)
RadioVolUp = 221		; Default = ] (221)
RadioVolDown = 219		; Default = [ (219)

[SFX]
Volume = 0.80			; Default = 0.35

; Keys																										
; 8	=>	Backspace                    57	=>	9						 92		=>	(right Windows key)		123	=>	F12
; 9	=>	Tab                          65	=>	A						 93		=>	(application key)		144	=>	Num Lock
; 13	=>	Enter                    66	=>	B                        96		=>	0 (numpad)				145	=>	Scroll Lock
; 16	=>	Shift (both)             67	=>	C                        97		=>	1 (numpad)          	186	=>	;
; 17	=>	Ctrl (both)              68	=>	D                        98		=>	2 (numpad)          	187	=>	=
; 19	=>	Pause                    69	=>	E                        99		=>	3 (numpad)          	188	=>	,
; 20	=>	Caps Lock                70	=>	F                        100	=>	4 (numpad)          	189	=>	-
; 27	=>	Esc                      71	=>	G                        101	=>	5 (numpad)          	190	=>	.
; 32	=>	Spacebar                 72	=>	H                        102	=>	6 (numpad)          	191	=>	/
; 33	=>	Page Up                  73	=>	I                        103	=>	7 (numpad)          	192	=>	`
; 34	=>	Page Down                74	=>	J                        104	=>	8 (numpad)          	219	=>	[
; 35	=>	End                      75	=>	K                        105	=>	9 (numpad)          	220	=>	\
; 36	=>	Home                     76	=>	L                        106	=>	* (numpad)          	221	=>	]
; 37	=>	(left arrow)             77	=>	M                        107	=>	+ (numpad)          	222	=>	'
; 38	=>	(up arrow)               78	=>	N                        109	=>	- (numpad)
; 39	=>	(right arrow)            79	=>	O                        110	=>	. (numpad)
; 40	=>	(down arrow)             80	=>	P                        111	=>	/ (numpad)
; 45	=>	Insert                   81	=>	Q                        112	=>	F1
; 46	=>	Delete                   82	=>	R                        113	=>	F2
; 48	=>	0                        83	=>	S                        114	=>	F3
; 49	=>	1                        84	=>	T                        115	=>	F4
; 50	=>	2                        85	=>	U                        116	=>	F5
; 51	=>	3                        86	=>	V                        117	=>	F6
; 52	=>	4                        87	=>	W                        118	=>	F7
; 53	=>	5                        88	=>	X                        119	=>	F8
; 54	=>	6                        89	=>	Y                        120	=>	F9
; 55	=>	7                        90	=>	Z                        121	=>	F10
; 56	=>	8                        91	=>	(left Windows key)       122	=>	F11																                                                                        	