[Settings]
	
Postman = 1				# 1 - enable, 0 - disable.
Garbage Mans = 1			# 1 - enable, 0 - disable.
Communication repairers = 1		# 1 - enable, 0 - disable.
WindWash = 1				# 1 - enable, 0 - disable.
Street Art = 1				# 1 - enable, 0 - disable.
Road Workers = 1			# 1 - enable, 0 - disable.
Sweeper Car = 1				# 1 - enable, 0 - disable.
Fire Scene = 1				# 1 - enable, 0 - disable.
Ottos Auto = 1				# 1 - enable, 0 - disable.
Gangs With Music = 1			# 1 - enable, 0 - disable.
Street musicians = 1			# 1 - enable, 0 - disable.
Street Cleaners = 1			# 1 - enable, 0 - disable.
Fish Rod = 1				# 1 - enable, 0 - disable.
Security Van Heist = 1			# 1 - enable, 0 - disable.
Car breakdown Event = 1			# 1 - enable, 0 - disable. (NPC car breakdown engine, tire)
Police Car Event = 1			# 1 - enable, 0 - disable. (arrest random guy)
In car Event = 1			# 1 - enable, 0 - disable. (chat in car, read newspaper, drink)
Peds use Vends = 1			# 1 - enable, 0 - disable. 
Food in the player hand	= 1		# 1 - enable, 0 - disable. (pizza, burger, ice cream, etc.)
Player can use umbrella = 1		# 1 - enable, 0 - disable. (key setting from below)
Pickup thieves = 1			# 1 - enable, 0 - disable.	
Shopping basket = 1			# 1 - enable, 0 - disable.


[Percent Chance]
Rap Battles = 80			# 0-100 %
Street Fight = 100			# 0-100 %
Parachute Ped =	70			# 0-100 %
Baseball = 90				# 0-100 %
Bum = 80 				# 0-100 %
Cops Search Peds = 30			# 0-100 %
Door In Out Peds = 70			# 0-100 %
Graffity Gang = 50			# 0-100 %
Hunter = 80				# 0-100 %
Police Crime Scene = 65			# 0-100 %
Tourist = 60				# 0-100 %
Monk = 40				# 0-100 %
Video News = 60				# 0-100 %
Arm wrestling = 70			# 0-100 %
People in the pool = 50			# 0-100 %
Boombox = 70				# 0-100 %
Rc Car Players = 60			# 0-100 %
Bus Station = 80			# 0-100 %
Street Dice = 80			# 0-100 %

[News Paper]
Price = 1				# 1$
Price Weekend = 2			# 2$

[Peds throwing garbage]
Time Peds throw again = 100		# seconds


[Fire Scene]
Time Fire Scene = 600			# seconds


[Car breakdown Event]
TimePause=150				# seconds, NPC car breakdown engine, tire


[Police Car Event]
TimePause=160				# seconds, arrest random guy
TimePause2=20				# seconds, m4 from car back	


[In car Event]
TimePause=20				# seconds, chat in car, read newspaper, drink 


[Peds use Vends]
Time for find next ped = 10		# Seconds

[Mr Whoopee]
Ped Position Offset X = -0.26
Ped Position Offset Y = -0.36
Ped Position Offset Z = 0.4


[Postman]
Ped ID = 208
Ped ID Bike = 265


[Garbage Mans]
Props = 1 				# 1 - enable, 0 - disable. enable If you use urbanize or project props;
Ped ID Driver = 260
Ped ID 1 = 260
Ped ID 2 = 260


[Communication repairers]
PED ID = 27

[Repairers]
PED ID = 260


[Sweeper Car]
Particle = 1				# 1 - enable, 0 - disable.


[Security Van Heist]
Money Parked Min = 500			# Random from Min to Max
Money Parked Max = 1000

Money Default Min = 1000
Money Default Max = 3000

Money Stealth Min = 3000
Money Stealth Max = 5000
	
Driver Weapon ID = 31			# Weapon ID
Driver Weapon Model = 356		# Weapon Model

Passenger Weapon ID = 27		# Weapon ID	
Passenger Weapon Model = 351		# Weapon Model

Maximum Wanted level = 4


[Street Cleaners]
Ped ID Broom = 183
Ped ID Rake = 136
Ped ID Watercan = 225
Ped ID Axe = 158
Ped ID Sledge = 27


[Gangs With Music]
Max Volume Actor = 0.7			# 0.0 - 1.0
Max Volume Car = 0.9			# 0.0 - 1.0
Key Skip Song = 82			# 82 - R
Number of songs = 5			# Caution! If you increase the number, you will need 								mp3 files for each group. if = 26 (B_7_26, B_8_26, B_9_26).

[Music from cars]
Volume = 0.8
Pause Time Day = 10		# Seconds
Pause Time Night = 50		# Seconds
				# The script searches for the car for 5 seconds, and after 							# that, if it does not find it, it pauses (Day/Night)

				# Number of songs
Radio ID 1 = 3			# Playback Fm
Radio ID 2 = 3			# K-Rose
Radio ID 3 = 3			# K-DST
Radio ID 4 = 3			# Bounce FM
Radio ID 5 = 3			# SF-UR
Radio ID 6 = 3			# Radio Los Santos
Radio ID 7 = 3			# Radio X
Radio ID 8 = 3			# CSR
Radio ID 9 = 3			# K-Jah
Radio ID 10 = 3			# Master Sound

				# if you want to add more tracks to a radio station, 
				# for example, Playback, then the file will be named
				# "1_(6).mp3" and in string "Radio ID 1 = 6"

[Street musicians]
Guitar volume = 0.8
Guitar voice = 1.0
Guitar Maximum Songs = 5		# G*.mp3
Elguitar Maximum Songs = 5		# EL*.mp3

Piano volume = 1.0
Piano voice = 1.0
Piano Maximum Songs = 5			# P*.mp3

Sax volume = 0.8
Sax voice = 1.0
Sax Maximum Songs = 5			# S*.mp3
Sax InhandX = 0.0			# Position in hand PEd №1
Sax InhandY = 0.0
Sax InhandZ = 0.0
Sax InhandX2 = 0.01			# Position in hand PEd №2
Sax InhandY2 = 0.0
Sax InhandZ2 = -0.04

Viol volume = 0.8
Viol voice = 1.0
Viol Maximum Songs = 5			# V*.mp3
Viol InhandX = 0.04			# Position in hand PEd №1
Viol InhandY = -0.02
Viol InhandZ = -0.4
Viol InhandX2 = 0.04			# Position in hand PEd №1
Viol InhandY2 = -0.02
Viol InhandZ2 = -0.4

Band volume = 0.8
Band voice = 1.0


[Fish Rod]
Reefer X = 1.0				# Boat offset position
Reefer Y = -2.1
Reefer Z = 1.0

Marquis X = 1.5
Marquis Y = -5.6
Marquis Z = 2.1

Dinghy X = 0.0
Dinghy Y = -0.8
Dinghy Z = 1.0


[Monk]
Volume = 0.5				# 0.0 - 1.0

[Tram]
X1 = -0.8
Y1 = 1.7
Z1 = 0.25 

X2 = 0.0
Y2 = -3.65
Z2 = 0.0

X3 = -0.7
Y3 = -1.1
Z3 = 0.25 

X4 = 0.7
Y4 = -1.45
Z4 = 0.25 

X5 = 0.8
Y5 = 3.0
Z5 = 0.25 

[Improved interiors]
GYM = 1					# 1 - enable, 0 - disable.
Garage = 1				# 1 - enable, 0 - disable.
Club = 1				# 1 - enable, 0 - disable.
Chef = 1				# 1 - enable, 0 - disable.
Barber = 1				# 1 - enable, 0 - disable.
AmmuNation= 1				# 1 - enable, 0 - disable.

Chef PIZZA PED ID = 155
Chef BURGER PED ID = 205
Chef CLUCKIN PED ID = 167
Cleaner PIZZA PED ID = 155
CLeaner BURGER PED ID = 205



[Player can use umbrella]
Main Key = 82		# 82 - R.
Enable = 49		# 49 - 1. (Main key + Enable)
Disable = 49		# 49 - 1. (Main key + Disable)
Change Hand = 50	# 50 - 2. (Main key + Change Hand)
Change Color = 51	# 51 - 3. (Main key + Change Color)

